# Dependencies
markdown:      redcarpet
highlighter:   pygments

# Permalinks
permalink:     pretty

# Setup
title:         jihopark
tagline:       'jihopark'
description:   'I write about machine learning, NLP, AI and product dev.'
url:           'http://me.jiho-ml.com'

author:
  name:        'jihopark'
  url:         'http://me.jiho-ml.com'

paginate:      5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-relative-links

# Custom vars
version:       2.1.0

github:
  repo:        https://github.com/poole/hyde
